INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('IT_Praesentation_2024.pptx',277888,010224);
INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('test.txt',4,020224);
INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('File.docx',13403,030224);

INSERT INTO USERS (USERNAME, USER_TYPE, PASSWORD_HASH, PASSWORD_SALT) Values ('test', 'USER','mWl5EWPAtC4brUIzM27qUCpCMPePJ2RX0ehc/Ajd/ds=','b3130cde-1a89-44f0-9603-d7dee2b05225');
INSERT INTO USERS (USERNAME, USER_TYPE, PASSWORD_HASH, PASSWORD_SALT) Values ('user', 'USER','10jXwVoXmR8DEKth4D0Xm7x3VLVxmOISbNfihyRMguM=','e7e32972-76f6-4e99-934a-bf47ec7aaeda');

INSERT INTO GROUPS_TABLE (GROUP_NAME) VALUES ('ADMINISTRATORS');
INSERT INTO GROUPS_TABLE (GROUP_NAME) VALUES ('USERS');

INSERT INTO PEERS_ST (ID,PEER_TYPE, TOTAL_SPACE, IP_ADDRESS, PORT) VALUES ('74-4C-A1-48-3B-5F','SUPERPEER', 2000000000,'10.232.33.171',5192);

INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (1,'74-4C-A1-48-3B-5F',0);
INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (2,'74-4C-A1-48-3B-5F',0);
INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (3,'74-4C-A1-48-3B-5F',0);

INSERT INTO USERS_HAS_ACCESS_TO_DATA_JT_ST (USER_ID,DATA_ID, OWNERSHIP_TYPE,UserId1) VALUES (1,1, 'OWNER', 1);
INSERT INTO USERS_HAS_ACCESS_TO_DATA_JT_ST (USER_ID,DATA_ID, OWNERSHIP_TYPE,UserId1) VALUES (1,2, 'OWNER', 1);
INSERT INTO USERS_HAS_ACCESS_TO_DATA_JT_ST (USER_ID,DATA_ID, OWNERSHIP_TYPE,UserId1) VALUES (1,3, 'NONE', 1);

INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,1,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,2,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,3,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (2,1,'READER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (2,2,'READER');

INSERT INTO USER_HAS_USER_GROUP_JT (USER_ID, GROUP_ID) VALUES (1,1);




