INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('IT_Praesentation_2024.pptx',277888,010224);
INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('Test',4,020224);
INSERT INTO DATA (NAME, SIZE, UPLOAD_TIME) VALUES ('File.docx',13403,030224);

INSERT INTO USERS (USERNAME, USER_TYPE, PASSWORD_HASH, PASSWORD_SALT) Values ('test', 'USER','mWl5EWPAtC4brUIzM27qUCpCMPePJ2RX0ehc/Ajd/ds=','b3130cde-1a89-44f0-9603-d7dee2b05225');

INSERT INTO 'GROUPS' (GROUP_ID, GROUP_NAME) VALUES (1, 'ADMINISTRATORS');
INSERT INTO 'GROUPS' (GROUP_ID, GROUP_NAME) VALUES (2, 'USERS');

INSERT INTO PEERS_ST (ID,PEER_TYPE, TOTAL_SPACE, IP_ADDRESS, PORT) VALUES ('74-4C-A1-48-3B-5F','SUPERPEER', 2000000000,'10.232.33.171',5192);

INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (1,'74-4C-A1-48-3B-5F',0);
INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (2,'74-4C-A1-48-3B-5F',0);
INSERT INTO DATA_SAVED_ON_PEERS_JT (DATA_ID, PEER_ID, SEQUENCE_NUMBER) VALUES (3,'74-4C-A1-48-3B-5F',0);

INSERT INTO USERS_HAS_ACCESS_TO_DATA_JT_ST (USERNAME, DATA_ID, OWNERSHIP_TYPE, Username1) VALUES ('test', 1, 'OWNER', 'test');

INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,1,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,2,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (1,3,'OWNER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (2,1,'READER');
INSERT INTO GROUP_HAS_DATA_JT_ST (GROUP_ID, DATA_ID, OWNERSHIP_TYPE) VALUES (2,2,'READER');

INSERT INTO USER_HAS_USER_GROUP_JT (USERNAME, GROUP_ID) VALUES ('test',1);




